### ISSUE TITLE
Another case with user-scalable=yes

### ISSUE THREAD

**Issue by ymaz** [bendrucker/meta-viewport-ios9#1]
Hi, thanks for your fix.

But, i would like to discus another case:
what do you think about workaround for the following viewport settings

initial-scale=1, minimum-scale=1, maximum-scale=2, user-scalable=yes

So, to leave for the user the possibility to scale web app with standard pitch zoom. (like we have on ios8).

Does it achievable with safari in ios9 ?

Thanks.

**Comment by bendrucker** [comment]
Hmm yeah that makes sense. I'll release a new version where the export value is a function that can take overrides.

**Comment by bendrucker** [comment]
Ended up electing to export an object by default in 2.0 with the string available at `/string`. You can just grab the object, make a copy with whatever changes you'd like, and then use `meta-string` directly to stringify the result.
